name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release-linux:
    name: "Pre Release Linux"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: "Update pip"
        run: |
          python -m pip install --upgrade pip
          sudo apt install protobuf-compiler
      
      - name: "Setup project"
        run: bash setup.py

      - name: "Deploy binaries"
        run: bash deploy.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-linux"
          prerelease: true
          title: "Pre Release Linux"
          files: |
            *.zip

  pre-release-windows:
    name: "Pre Release Windows"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: "Update pip"
        run: |
          python -m pip install --upgrade pip

      - name: "Setup project"
        run: .\setup.bat

      - name: "Deploy binaries"
        run: .\deploy.bat

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-windows"
          prerelease: true
          title: "Pre Release Windows"
          files: |
            *.zip
